Implemented completion for dictionary items
robocorp/robotframework-lsp pull request #401
Opened 2021-07-18 15:45 UTC by mardukbp

Dictionary items can now be completed using the syntax

```
${dict}[some index][another index]
```

That is, dictionary items, which are themselves dictionaries are also handled.

The code is meant to be short and simple. Feel free to adapt it as you see fit.

2021-07-19 12:01 UTC, fabioz requested changes
Thanks for the pull request.

I made some general comments which I believe are straightforward to address.

Also, this pull request needs some tests along with it.

You can add create a new `test_dictionary_variables_completions.py` for this feature based on:
https://github.com/robocorp/robotframework-lsp/blob/master/robotframework-ls/tests/robotframework_ls_tests/completions/test_variables_completions.py.

2021-07-25 10:52 UTC, mardukbp commented on robotframework-ls/src/robotframework_ls/impl/dictionary_completions.py
> +def get_variables(completion_context):
Done

2021-07-25 10:55 UTC, mardukbp commented on robotframework-ls/src/robotframework_ls/impl/dictionary_completions.py
> +    for node_info in ast_utils.iter_variables(ast):
Done. I think it is better to refactor variable_completions to use CompletionContext.get_all_variables after merging this PR.

2021-07-25 10:55 UTC, mardukbp commented on robotframework-ls/src/robotframework_ls/impl/dictionary_completions.py
> +        var_name = node.get_token(Token.VARIABLE).value
Done.

2021-07-25 10:55 UTC, mardukbp commented on robotframework-ls/src/robotframework_ls/impl/dictionary_completions.py
> +    dict_variable_regex = re.compile(r"[$|&]{(\w+)}")
Done.

2021-07-25 10:55 UTC, mardukbp commented on robotframework-ls/src/robotframework_ls/impl/dictionary_completions.py
> +def get_dict_name(dict_item_access):
Done.

2021-07-25 10:55 UTC, mardukbp commented on robotframework-ls/src/robotframework_ls/impl/dictionary_completions.py
> +def get_dict_keys(dict_item_access):
Done.

2021-07-25 10:56 UTC, mardukbp commented on robotframework-ls/src/robotframework_ls/impl/dictionary_completions.py
> +    dict_key_regex = re.compile(r"\[([\w\s]*)\]")
Done.

2021-07-25 10:56 UTC, mardukbp commented on robotframework-ls/src/robotframework_ls/impl/dictionary_completions.py
> +def get_dictionary(variables, dict_name, dict_keys):
Done.

2021-07-25 10:56 UTC, mardukbp commented on robotframework-ls/src/robotframework_ls/impl/dictionary_completions.py
> +def as_dictionary(dict_tokens):
Done.

2021-07-25 10:56 UTC, mardukbp commented on robotframework-ls/src/robotframework_ls/impl/dictionary_completions.py
> +def completion_items(dictionary, editor_range):
Done.

2021-07-25 10:56 UTC, mardukbp commented on robotframework-ls/src/robotframework_ls/impl/dictionary_completions.py
> +def complete(completion_context):
Done.

2021-07-25 10:59 UTC, fabioz commented on robotframework-ls/tests/robotframework_ls_tests/completions/test_dictionary_entries_completions.py
> +    data_regression.check(completions)
The actual files related to the data regression aren't added (so, tests will fail in the ci).

2021-07-26 17:43 UTC, merged

2021-07-26 17:43 UTC, fabioz commented
Just merged. Thanks for the pull request.